export const selectedProjects = [
  {
    id: 0,
    title: "Shopping Cart Project",
    used: ["react", "tailwindCSS", "reactRouting", "chakraUI"],
    description: "An assigned project from The Odin Project in this project you are tasked to a basic ecomerce website using the fakestore API, having mutiple pages, and having a shopping cart in the e comerce app. In this project I learned about pulling data from an API, using the useEffect react hook, react routing, using the contextAPI, and styling the side using ChakraUI and TailwindCSS",
    imageLink: "/project-thumbnails/shoppingcartpict.png",
    liveLink: "https://shopping-cart-project-inky.vercel.app/",
    codeLink: "https://github.com/aliflikescoding/react-shopping-cart",
    slugLink: "#",
  },
  {
    id: 1,
    title: "React Blood Bank",
    used: ["react", "tailwindCSS", "reactRouting", "chakraUI"],
    description: "A commitioned work that I did converting figma designes to a live code version using ReactJS, ChartJS, ChakraUI, and tailwind css, In this project I used basic routing using react router. In this project I learned about processing data using chartJS and ChakraUI, Basic routing using react route, and styling using Tailwind CSS",
    imageLink: "/project-thumbnails/bloodbank.png",
    liveLink: "https://blood-bank-project-inky.vercel.app/",
    codeLink: "https://github.com/aliflikescoding/react-blood-bank",
    slugLink: "#",
  },
  {
    id: 2,
    title: "Vanilla Battleship",
    used: ["HTML", "SASS", "Javascript", "JEST"],
    description: "you An assigned project from The Odin Project in this project you are assgined to make a clasic battleship game using html, css, and javasript but I used sass isntead. you arer assigned to use OOP to make the ships and JEST to test the project. In this project I learned about advaced OOP in javascript unit testing javascript logic using JEST",
    imageLink: "/project-thumbnails/battleship.png",
    liveLink: "https://aliflikescoding.github.io/vanilla-battleship/",
    codeLink: "https://github.com/aliflikescoding/vanilla-battleship",
    slugLink: "#",
  },
  {
    id: 3,
    title: "Vanilla To Do List",
    used: ["HTML", "CSS", "Javascript"],
    description: "An assigned project from TOP (the odin project) course. You are tasked to build a To Do List App using vanilla html, css, and Javasript. In this project I learend about OOP intensively in javascript",
    imageLink: "/project-thumbnails/todolist.png",
    liveLink: "https://aliflikescoding.github.io/vanilla-to-do-list/",
    codeLink: "https://github.com/aliflikescoding/vanilla-to-do-list",
    slugLink: "#",
  },
  {
    id: 4,
    title: "Vanilla To Do List",
    used: ["Webflow", "Web Design"],
    description: "This is a homepage design and build for a concept project – a chat application. I designed the page first then built a responsive web page using Webflow.",
    imageLink: "/project-thumbnails/webflowchatapp.png",
    liveLink: "https://aliflikescoding-team-app.webflow.io/",
    codeLink: "#",
    slugLink: "#",
  },
]