import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Aliflikescoding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" /> {/* Add this line for favicon */}
      </head>
      <body className="bg-customCream text-customBlack font-poppins">
        {children}
      </body>
    </html>
  );
}
